### ISSUE TITLE
remove the switch section

### ISSUE THREAD

**Issue by lasse9000** [OttoWinter/esphomedocs#119]
Is there a way to make the automation so the button toggle the light-switch, so i can remove the switch section completly.

binary_sensor:

platform: gpio
pin:
number: GPIO0
mode: INPUT_PULLUP
inverted: True
name: "Sonoff 4CH Button 1"
on_press:
switch.toggle: relay_1
output:

platform: gpio
pin: GPIO12
id: gpio_d1
light:

platform: binary
name: "Køkkenbord"
output: gpio_d1

i have tryed:
-light.toggle: relay_1
-light.toggle: gpio_d1
-switch.toggle: relay_1
-switch.toggle: gpio_d1
but an id: in the light

**Comment by OttoWinter** [comment]
```yaml
binary_sensor
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Sonoff 4CH Button 1"
  on_press:
    - light.toggle: light_1
output:
- platform: gpio
  pin: GPIO12
  id: gpio_d1
light:
- platform: binary
  name: "Køkkenbord"
  output: gpio_d1
  id: light_1
```
