### ISSUE TITLE
Slampher relay pin

### ISSUE THREAD

**Issue by swhaat** [OttoWinter/esphomedocs#134]
I have successfully flashed a sonoff slampher, but as i used pin GPIO3, from the docs, the device relay was irresponsive.
I changed it to GPIO12, as most other sonoffs and it worked.
Originally it had firmware v1.6.2.
Maybe someone else can test these settings?
Button on GPIO0 did work.

**Comment by meijerwynand** [comment]
I am also running a Slampher and can confirm the relay is on GPIO12.
```yaml
...
  ## Relay / light
  - platform: gpio
    pin: GPIO12
    name: "esp_bench_light_gpio12"
    id: esp_bench_light_gpio12
...
```

The link https://esphomelib.com/esphomeyaml/devices/sonoff.html?highlight=slampher#slampher does show GPIO3 in the above link, however, it appears GPIO3 is a data / serial / uart pin.

Must be a typo in esphomedocs: the main link mentioned in the introduction of the above mentioned page ( https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/sonoff_template.h#L738 ) documentation also references GPIO12 as the relay pin
