### ISSUE TITLE
Wrong indentation in Pulse Counter docs example

### ISSUE THREAD

**Issue by DanielJutz** [OttoWinter/esphomedocs#2386]
### The problem

I believe that the [counting total pulses](https://esphome.io/components/sensor/pulse_counter.html#counting-total-pulses) example in the docs has the code starting with `pin: 12` indented once too many times

```
# Example configuration entry
sensor:
- platform: pulse_counter
    pin: 12
    unit_of_measurement: 'kW'
    name: 'Power Meter House'
    filters:
      - multiply: 0.06  # (60s/1000 pulses per kWh)

    total:
      unit_of_measurement: 'kWh'
      name: 'Energy Meter House'
      filters:
        - multiply: 0.001  # (1/1000 pulses per kWh)
```

should be 

```
# Example configuration entry
sensor:
- platform: pulse_counter
  pin: 12
  unit_of_measurement: 'kW'
  name: 'Power Meter House'
  filters:
    - multiply: 0.06  # (60s/1000 pulses per kWh)

  total:
    unit_of_measurement: 'kWh'
    name: 'Energy Meter House'
    filters:
      - multiply: 0.001  # (1/1000 pulses per kWh)
```

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266
