### ISSUE TITLE
Changed availability_topic and discovery

### ISSUE THREAD

**Issue by Yevgenium** [OttoWinter/esphomedocs#74]
Hello
If I change topics for LWT messages (from `nodemcu/status` to `nodemcu/state` in this example)
```
mqtt:
  broker: '10.0.0.53'
  username: 'hassio'
  password: '1234567'
  client_id: nodemcu
  discovery: true
  log_topic: nodemcu/log
  birth_message:
    topic: nodemcu/state
    payload: online
  will_message:
    topic: nodemcu/state
    payload: offline
```
 I do not get modified topics in autodiscovery messages

`homeassistant/sensor/nodemcu/bmp180_pressure/config`:
`{"unit_of_measurement":"hPa","expire_after":675,"icon":"mdi:gauge","name":"BMP180 Pressure","state_topic":"nodemcu/bmp180_pres","availability_topic":"nodemcu/status","unique_id":"ESPsensorbmp180_pressure","device":{"identifiers":"5ccf7fdc3c1d","name":"nodemcu","sw_version":"esphomelib v1.9.0b1 Nov  3 2018, 15:37:10","model":"PLATFORMIO_NODEMCUV2","manufacturer":"espressif"}}`
