### ISSUE TITLE
time servers list formatting , need a sample

### ISSUE THREAD

**Issue by voicevon** [OttoWinter/esphomedocs#93]
I am creating a sntp_time , So I followed here
`https://esphomelib.com/esphomeyaml/components/time.html`
But the document is not clearly show how to write yaml code of servers list.'  I tried this:
```
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-8
    servers:  0.pool.ntp.org, 1.pool.ntp.org , 2.pool.ntp.org
    

  // and I got the codes in main.cpp

  time::SNTPComponent *sntp_time = App.make_sntp_component();
  sntp_time->set_servers("0.pool.ntp.org, 1.pool.ntp.org , 2.pool.ntp.org", "", "");

//The declaration  is 
void esphomelib::time::SNTPComponent::set_servers(const std::string &server_1, const std::string &server_2, const std::string &server_3)
``
Obviously my Yaml is wrong. I couldn't find a correct sample in this document.

**Comment by OttoWinter** [comment]
The syntax is a normal YAML list, for example:

```yaml
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-8
    servers: 
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
```

or 

```yaml
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-8
    servers:  [0.pool.ntp.org, 1.pool.ntp.org , 2.pool.ntp.org]
```
